#!/bin/sh

# to set the MIME type to text/css since text/plain makes it so the css fails to apply even thought the Network developer tab shows that the file is downloading properly
(cd ~/Dropbox/PhotoPublishing && s3cmd --acl-public put -m "text/css" UpdikeOrg/nitpic/base.css s3://updike-org/PhotoPublishing/UpdikeOrg/nitpic/base.css)
